language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r test_requirements.txt
  - pip install . 
script:
  - py.test tests/*Test.py --cov=sonyapilib
  - pylint sonyapilib
  - coveralls