language: python
python:
  - "3.6"
cache: pip
install:
  - pip install python-coveralls
  - pip install -r test_requirements.txt
  - pip install . 
script:
  - py.test tests/*Test.py --cov=sonyapilib
  - pylint tests/*Test.py
  - coveralls